release-date = "2021-08-09"

[[entries]]
id = "094e530c-e328-4136-91d4-c9ede00e73f0"
type = "fix"
description = "HugoRenderer: Restore old behaviour for `HugoConfig.additional_options`, which should be deserialized flat (i.e. it takes on any additional options in the same object that can not be mapped to any other fields of the config object)"
author = "@NiklasRosenstein"
