release-date = "2022-03-05"

[[entries]]
id = "69632097-79eb-4381-89c9-5ba4bd2f926f"
type = "fix"
description = "fix recognition of overwritten values in `MarkdownRenderer.header_level_by_type`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/249"
issues = [
    "https://github.com/NiklasRosenstein/pydoc-markdown/issues/248",
]

[[entries]]
id = "0129cf1b-9df5-43b2-9915-a904cf5ef3a0"
type = "fix"
description = "fix backwards compat of handling `\"Data\"` key in `MarkdownRenderer.header_level_by_type` when now it should be `\"Variable\"`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/249"
