release-date = "2022-11-13"

[[entries]]
id = "61d34362-5fc1-474f-9c19-bead33b9ddc7"
type = "improvement"
description = "add explicit compatibility with Novella 0.2.x (`>=0.1.10,<0.3.0`)"
author = "@NiklasRosenstein"

[[entries]]
id = "e1e8f57c-4f39-4f89-9cb3-18dbc29dedf4"
type = "docs"
description = "Fix installation instructions using Pipx (#256)"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/pydoc-markdown/issues/256",
]

[[entries]]
id = "4ffc08fa-99d0-41b5-bd71-b56ff99639d7"
type = "fix"
description = "fix interpreting Markdown in-document anchor links as cross references"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/pydoc-markdown/issues/274",
]

[[entries]]
id = "f2ec6f82-8b97-4b9e-9b13-dbc315814a40"
type = "fix"
description = "fix generated code for class signature with not base class and a metaclass parameter"
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/pydoc-markdown/issues/272",
]
