release-date = "2022-03-13"

[[entries]]
id = "f2e4f7fa-d53e-4481-85b8-57749532c73e"
type = "fix"
description = "fix AttributeError when using a Git source linker with `use_branch` disabled"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/issues/252"
issues = [
    "https://github.com/NiklasRosenstein/pydoc-markdown/issues/250",
]

[[entries]]
id = "b3776b2e-53bd-46a9-9970-e8d53a61f04f"
type = "hygiene"
description = "remove unused functions that interact with Git since the same functionality from the `nr.utils.git` module is used instead now"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/issues/252"
