release-date = "2023-05-28"

[[entries]]
id = "4409675c-ea67-4c56-be5a-a7310f779c15"
type = "improvement"
description = "Change `PythonLoader.encoding` default value from `None` (system default) to `utf-8`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/282"

[[entries]]
id = "01003f02-89ec-46d5-9809-4cacf51547fa"
type = "improvement"
description = "Support parsing all types of docstring formats that are supported by the `docstring_parser` module in `SphinxProcessor`, not just ReST"
author = "@hippalectryon-0"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/282"

[[entries]]
id = "b2ac1e9f-fcf3-4821-a9dd-5a9e13afd7ba"
type = "fix"
description = "No longer HTML-escape text in Markdown code blocks."
author = "@hippalectryon-0"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/282"

[[entries]]
id = "b3fe8391-64a2-46fb-a7f2-2b0e2202fa13"
type = "fix"
description = "Fix codeblocks rendering to maintain indentation as per the original docstring."
author = "@hippalectryon-0"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/283"
issues = [
    "https://github.com/NiklasRosenstein/pydoc-markdown/issues/169",
]

[[entries]]
id = "c4423f29-5191-4579-b07b-98981799fb44"
type = "improvement"
description = "Allow Pyyaml `^6.0` in addition to `^5.0`"
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/287"

[[entries]]
id = "71954726-75bc-4000-bfff-c7c2a47cebc6"
type = "improvement"
description = "Undeprecated YAML-based configuration for Pydoc-Markdown."
author = "@NiklasRosenstein"
pr = "https://github.com/NiklasRosenstein/pydoc-markdown/pull/288"
issues = [
    "https://github.com/NiklasRosenstein/pydoc-markdown/issues/286",
]

[[entries]]
id = "4e48b4c1-06bc-43e2-a848-870a6fa31ae3"
type = "docs"
description = "Update docs to inform user that `mkdocs` with `mkdocs-material` must be installed in Novella Usage guide."
author = "@NiklasRosenstein"
issues = [
    "https://github.com/NiklasRosenstein/pydoc-markdown/issues/270",
]
