version: 2
mkdocs: {}  # tell readthedocs to use mkdocs
python:
  version: 3.7
  install:
  - {method: pip, path: pydoc-markdown}
  - requirements: readthedocs-custom-steps nr.shore==1.0.1
x-custom-steps:
  - shore changelog --all --markdown >CHANGELOG.md
  - pydoc-markdown --build --site-dir $SITE_DIR
