steps:
# We install Pydoc-Markdown into a separate Virtualenv to avoid dependency conflicts with `shut`.
- /home/docs/.pyenv/shims/python3.7 -m virtualenv .venv
- .venv/bin/python -m pip install .
- .venv/bin/pydoc-markdown --build --site-dir $SITE_DIR -vv
