name: pydoc-markdown-readthedocs-mkdocs-proxy
version: 0.0.0
author:
  name: Niklas Rosenstein
  email: rosensteinniklas@gmail.com
description: Package description here.
requirements:
- python ^3.5
- pydoc-markdown ^3.0.0
install-hooks:
- install: bin/install.py
