steps:
# We install Pydoc-Markdown into a separate Virtualenv to avoid dependency conflicts with `shut`.
- |
  "$PYTHON" -m virtualenv .venv
  .venv/bin/python -m pip install .
  .venv/bin/pydoc-markdown --build --site-dir _build/html -vv
